import type { MicroteachingBriefSeed } from "./types";

export const microteachingBriefs: MicroteachingBriefSeed[] = [
  {
    slug: "membuka-tema-binatang-tanpa-gambar",
    title: "Membuka Tema Binatang Tanpa Gambar Cetak",
    ageRange: "4-5 tahun",
    childCount: 12,
    durationMinutes: 15,
    theme: "Binatang",
    constraint: "Tidak ada printer dan tidak ada poster binatang; hanya ada tubuhmu, suara, dan benda-benda kelas.",
    goal: "Membuka kegiatan dengan menarik sehingga semua anak penasaran dalam 3 menit pertama.",
    hints: [
      "Apa yang bisa anak tebak hanya dari suara atau gerakan tubuhmu?",
      "Bagaimana caramu membuat anak yang duduk paling belakang ikut menoleh?",
      "Pikirkan satu benda misterius yang bisa memancing tebakan sebelum tema diumumkan.",
    ],
  },
  {
    slug: "transisi-halus-cuci-tangan-ruang-sempit",
    title: "Transisi dari Bermain ke Cuci Tangan di Ruang Sempit",
    ageRange: "5-6 tahun",
    childCount: 18,
    durationMinutes: 10,
    theme: "Kebersihan",
    constraint: "Ruangan sempit dengan satu wastafel; 18 anak tidak mungkin bergerak bersamaan.",
    goal: "Merancang transisi halus tanpa antrean panjang dan tanpa anak menganggur.",
    hints: [
      "Kelompok mana yang bergerak duluan, dan apa yang dilakukan kelompok yang menunggu?",
      "Sinyal apa yang menandai giliran tanpa kamu harus berteriak?",
      "Bisakah lagu atau tepukan menjadi pengatur waktu alami?",
    ],
  },
  {
    slug: "pertanyaan-terbuka-mengamati-kecambah",
    title: "Bertanya Terbuka Saat Mengamati Kecambah",
    ageRange: "5-6 tahun",
    childCount: 10,
    durationMinutes: 15,
    theme: "Tanaman",
    constraint: "Hanya ada tiga gelas kecambah untuk 10 anak; tidak semua bisa memegang bersamaan.",
    goal: "Mengajukan pertanyaan terbuka yang memancing anak mengamati, menduga, dan bercerita, bukan sekadar menjawab ya/tidak.",
    hints: [
      "Bandingkan: \"Ini akarnya ya?\" dengan \"Apa yang kamu lihat di bagian bawah?\" Mana yang membuka cerita?",
      "Bagaimana mengatur giliran memegang agar anak yang menunggu tetap mengamati?",
      "Siapkan satu pertanyaan lanjutan untuk jawaban anak yang tak terduga.",
    ],
  },
  {
    slug: "kelompok-kecil-mengenal-warna-satu-set-krayon",
    title: "Bermain Warna dengan Satu Set Krayon",
    ageRange: "3-4 tahun",
    childCount: 8,
    durationMinutes: 10,
    theme: "Warna",
    constraint: "Hanya ada satu set krayon berisi 12 batang untuk seluruh kelompok.",
    goal: "Mengelola kelompok kecil agar semua anak aktif meskipun alat harus bergiliran.",
    hints: [
      "Apakah kegiatan harus dimulai dengan memegang krayon, atau bisa dimulai dengan berburu warna di sekitar ruangan?",
      "Bagaimana aturan bergiliran dibuat terlihat dan dipahami anak 3 tahun?",
      "Apa peran anak yang sedang tidak memegang krayon?",
    ],
  },
  {
    slug: "bercerita-keluargaku-tanpa-buku",
    title: "Bercerita Tema Keluargaku Tanpa Buku",
    ageRange: "4-5 tahun",
    childCount: 15,
    durationMinutes: 15,
    theme: "Keluargaku",
    constraint: "Tidak ada buku cerita maupun boneka; cerita harus dibangun dari suara, ekspresi, dan partisipasi anak.",
    goal: "Menjaga perhatian 15 anak selama bercerita hanya dengan tubuh, suara, dan interaksi.",
    hints: [
      "Di titik mana anak bisa ikut menirukan suara atau gerakan tokoh?",
      "Bagaimana kamu mengubah volume dan tempo suara untuk membangun rasa penasaran?",
      "Apa pertanyaan pendek yang bisa kamu selipkan tanpa memutus alur cerita?",
    ],
  },
  {
    slug: "instruksi-bertahap-berburu-bentuk-listrik-mati",
    title: "Berburu Bentuk Saat Listrik Mati",
    ageRange: "5-6 tahun",
    childCount: 20,
    durationMinutes: 25,
    theme: "Bentuk",
    constraint: "Listrik mati: tidak ada speaker, proyektor, maupun kipas; ruangan hanya diterangi cahaya jendela.",
    goal: "Memberi instruksi bertahap yang jelas untuk 20 anak tanpa alat pengeras suara.",
    hints: [
      "Berapa langkah instruksi yang bisa diingat anak sekaligus? Coba pecah dan cek pemahaman sebelum lanjut.",
      "Sinyal non-listrik apa yang bisa mengumpulkan anak dari seluruh penjuru ruangan?",
      "Bagaimana cahaya jendela bisa jadi bagian dari permainan bentuk itu sendiri?",
    ],
  },
  {
    slug: "mengenal-emosi-untuk-anak-baru",
    title: "Mengenal Emosi Bersama Anak yang Baru Masuk",
    ageRange: "3-4 tahun",
    childCount: 10,
    durationMinutes: 15,
    theme: "Emosi",
    constraint: "Dua anak baru masuk minggu ini dan belum berani bicara; kegiatan tidak boleh memaksa mereka tampil.",
    goal: "Merancang kegiatan emosi yang memberi ruang partisipasi tanpa tekanan bagi anak pemalu.",
    hints: [
      "Bentuk partisipasi apa yang tidak menuntut bicara (menunjuk, mengangkat kartu, meniru wajah)?",
      "Bagaimana posisi dudukmu memengaruhi rasa aman anak baru?",
      "Apa yang kamu lakukan jika anak baru hanya mengamati sepanjang kegiatan?",
    ],
  },
  {
    slug: "eksplorasi-air-kelas-campur-usia",
    title: "Eksplorasi Air untuk Kelas Campur Usia",
    ageRange: "3-6 tahun",
    childCount: 16,
    durationMinutes: 20,
    theme: "Air",
    constraint: "Kelas campur usia 3-6 tahun dalam satu kegiatan; kemampuan motorik dan fokusnya sangat beragam.",
    goal: "Mendesain satu kegiatan dengan tingkat tantangan bertingkat agar anak kecil dan besar sama-sama tertantang.",
    hints: [
      "Tugas dasar apa yang bisa semua usia lakukan, dan lapisan tantangan apa untuk yang lebih besar?",
      "Bisakah anak besar mendapat peran membantu tanpa mengambil alih pekerjaan anak kecil?",
      "Di mana titik paling berisiko basah-licin, dan bagaimana mencegahnya sejak penataan?",
    ],
  },
  {
    slug: "penutupan-bermakna-tema-makanan",
    title: "Menutup Kegiatan Tema Makanan dengan Bermakna",
    ageRange: "4-5 tahun",
    childCount: 14,
    durationMinutes: 10,
    theme: "Makanan",
    constraint: "Waktu penutupan hanya 10 menit dan anak-anak masih bersemangat tinggi setelah kegiatan memasak sederhana.",
    goal: "Menutup kegiatan dengan refleksi sederhana yang menurunkan energi anak secara bertahap, bukan mendadak.",
    hints: [
      "Bagaimana urutan penutupan bisa bergerak dari gerakan besar ke suara pelan?",
      "Pertanyaan refleksi seperti apa yang bisa dijawab anak 4 tahun dari pengalaman langsungnya tadi?",
      "Apa ritual penutup singkat yang bisa jadi kebiasaan tetap kelas?",
    ],
  },
  {
    slug: "gerak-lagu-kendaraan-ruang-sempit",
    title: "Gerak dan Lagu Kendaraan di Ruangan Sempit",
    ageRange: "3-4 tahun",
    childCount: 12,
    durationMinutes: 10,
    theme: "Kendaraan",
    constraint: "Ruangan sempit dengan meja-kursi yang tidak bisa dipindah; ruang gerak hanya selebar karpet kecil.",
    goal: "Menyalurkan energi gerak anak dengan aman di ruang terbatas.",
    hints: [
      "Gerakan kendaraan apa yang bisa dilakukan di tempat tanpa berpindah (menyetir, mengayuh, terbang)?",
      "Bagaimana mengatur formasi agar anak tidak saling bertabrakan?",
      "Apa aba-aba \"rem\" yang membuat semua anak berhenti serentak dengan senang?",
    ],
  },
  {
    slug: "sains-cuaca-tanpa-alat-khusus",
    title: "Menyelidiki Cuaca Tanpa Alat Khusus",
    ageRange: "5-6 tahun",
    childCount: 12,
    durationMinutes: 20,
    theme: "Cuaca",
    constraint: "Tidak ada alat peraga sains; hanya jendela kelas, kertas bekas, dan benda sehari-hari.",
    goal: "Memfasilitasi anak menyelidiki dan menyimpulkan sendiri, bukan menerima penjelasan jadi.",
    hints: [
      "Apa yang bisa diamati anak langsung dari jendela hari ini, dan bagaimana mencatatnya tanpa menulis?",
      "Bagaimana kertas bekas bisa menjadi alat mendeteksi angin?",
      "Kapan kamu menahan diri untuk tidak langsung menjawab pertanyaan anak?",
    ],
  },
  {
    slug: "permainan-tradisional-halaman-becek",
    title: "Permainan Tradisional Saat Halaman Becek",
    ageRange: "5-6 tahun",
    childCount: 18,
    durationMinutes: 30,
    theme: "Budaya lokal",
    constraint: "Rencana bermain engklek di halaman batal karena becek; kegiatan harus pindah ke dalam ruangan.",
    goal: "Mengadaptasi permainan tradisional ke dalam ruangan tanpa kehilangan esensi budayanya.",
    hints: [
      "Bagian mana dari permainan itu yang paling penting dipertahankan: aturannya, geraknya, atau kebersamaannya?",
      "Apa pengganti garis kapur di lantai dalam ruangan yang aman dan mudah dibereskan?",
      "Bagaimana 18 anak tetap terlibat jika arena dalam ruangan hanya muat sedikit pemain?",
    ],
  },
  {
    slug: "mengenal-angka-tanpa-kartu-angka",
    title: "Bermain Angka Tanpa Kartu Angka",
    ageRange: "4-5 tahun",
    childCount: 15,
    durationMinutes: 15,
    theme: "Angka",
    constraint: "Tidak ada kartu angka, poster, atau lembar kerja; hanya benda-benda alam seperti daun, kerikil, dan ranting.",
    goal: "Mengenalkan konsep banyak-sedikit dan membilang lewat benda konkret, tanpa drill.",
    hints: [
      "Bagaimana anak bisa \"merasakan\" perbedaan banyak dan sedikit dengan tubuh atau tangan mereka?",
      "Permainan apa yang membuat anak membilang karena butuh, bukan karena disuruh?",
      "Bagaimana kamu tahu anak benar-benar memahami, bukan sekadar hafal urutan?",
    ],
  },
  {
    slug: "bermain-peran-profesi-properti-terbatas",
    title: "Bermain Peran Profesi dengan Properti Seadanya",
    ageRange: "5-6 tahun",
    childCount: 16,
    durationMinutes: 25,
    theme: "Profesi",
    constraint: "Tidak ada kostum atau properti profesi; hanya kardus bekas, kain perca, dan kursi kelas.",
    goal: "Memfasilitasi bermain peran yang hidup dengan mendorong anak menciptakan properti imajinatifnya sendiri.",
    hints: [
      "Apa jadinya jika anak yang memutuskan kardus itu menjadi apa, bukan kamu?",
      "Bagaimana membagi 16 anak ke beberapa \"pos profesi\" agar tidak berebut peran favorit?",
      "Kapan kamu masuk ke dalam permainan sebagai tokoh, dan kapan mundur jadi pengamat?",
    ],
  },
  {
    slug: "memilah-sampah-halaman-sekolah",
    title: "Memilah Sampah di Sekitar Sekolah",
    ageRange: "5-6 tahun",
    childCount: 14,
    durationMinutes: 20,
    theme: "Lingkungan",
    constraint: "Tidak ada tempat sampah terpilah di sekolah; wadahnya harus dibuat dari barang yang ada, dan keamanan memungut sampah harus dijaga.",
    goal: "Merancang kegiatan nyata yang bermakna sambil mengelola batas aman apa yang boleh dan tidak boleh disentuh anak.",
    hints: [
      "Aturan aman apa yang harus disepakati sebelum anak keluar kelas, dan bagaimana mengeceknya dipahami?",
      "Bagaimana anak bisa memilah tanpa menyentuh langsung benda yang berisiko?",
      "Apa tindak lanjut kecil yang membuat kegiatan ini tidak berhenti jadi acara sekali jalan?",
    ],
  },
  {
    slug: "literasi-awal-suara-binatang-tanpa-buku",
    title: "Bermain Bunyi Awal Kata dari Nama Binatang",
    ageRange: "4-5 tahun",
    childCount: 12,
    durationMinutes: 15,
    theme: "Binatang",
    constraint: "Tidak ada buku maupun kartu huruf; kesadaran bunyi harus dibangun murni lewat permainan lisan.",
    goal: "Melatih kesadaran fonologis (bunyi awal kata) lewat permainan, tanpa mengajarkan baca-tulis formal.",
    hints: [
      "Bagaimana anak bisa menebak binatang hanya dari bunyi awal namanya?",
      "Gerakan atau tepukan apa yang bisa menandai setiap bunyi awal agar terasa seperti permainan?",
      "Apa yang kamu lakukan jika ada anak yang selalu menjawab lebih dulu sehingga yang lain tidak sempat berpikir?",
    ],
  },
  {
    slug: "rotasi-pos-air-dua-ember",
    title: "Rotasi Pos Bermain Air dengan Dua Ember",
    ageRange: "5-6 tahun",
    childCount: 20,
    durationMinutes: 30,
    theme: "Air",
    constraint: "Hanya ada dua ember dan beberapa gelas plastik untuk 20 anak; area basah harus tetap terkendali.",
    goal: "Mengelola rotasi kelompok besar agar setiap anak mendapat giliran bermain air yang cukup tanpa kekacauan.",
    hints: [
      "Berapa pos yang kamu butuhkan, dan pos kering apa yang setara serunya dengan pos air?",
      "Bagaimana anak tahu kapan waktunya pindah pos tanpa kamu mengulang instruksi terus-menerus?",
      "Siapa yang mengelap tumpahan, dan bagaimana itu menjadi bagian dari kegiatan, bukan gangguan?",
    ],
  },
  {
    slug: "memancing-anak-pendiam-bicara-tema-emosi",
    title: "Mengajak Anak Pendiam Bercerita tentang Perasaan",
    ageRange: "4-5 tahun",
    childCount: 10,
    durationMinutes: 15,
    theme: "Emosi",
    constraint: "Tiga anak di kelompok ini hampir tidak pernah bicara di kegiatan kelompok, dan dua anak lain selalu mendominasi.",
    goal: "Menyeimbangkan partisipasi: memberi jalan masuk bagi anak pendiam tanpa membungkam anak yang aktif.",
    hints: [
      "Media apa yang bisa \"berbicara\" mewakili anak (boneka, kartu wajah, benda kesayangan)?",
      "Bagaimana struktur giliran melindungi ruang bicara anak pendiam?",
      "Peran istimewa apa yang bisa diberikan pada anak dominan agar energinya tersalur?",
    ],
  },
  {
    slug: "kegiatan-tenang-menunggu-jemputan",
    title: "Kegiatan Tenang Saat Menunggu Jemputan",
    ageRange: "3-4 tahun",
    childCount: 8,
    durationMinutes: 10,
    theme: "Keluargaku",
    constraint: "Tanpa persiapan sama sekali: kegiatan dadakan karena jemputan terlambat, anak sudah lelah, dan mainan sudah dibereskan.",
    goal: "Menghadirkan kegiatan tenang tanpa alat yang menjaga suasana positif pada anak yang lelah.",
    hints: [
      "Permainan jari dan bisik-bisik apa yang bisa dimainkan sambil duduk bersandar?",
      "Bagaimana anak yang dijemput duluan bisa pamit tanpa membuyarkan suasana?",
      "Apa yang kamu lakukan agar menunggu terasa seperti waktu istimewa, bukan hukuman?",
    ],
  },
  {
    slug: "tanya-jawab-setelah-cerita-anak-mudah-teralih",
    title: "Tanya Jawab Setelah Cerita untuk Anak yang Mudah Teralihkan",
    ageRange: "3-4 tahun",
    childCount: 12,
    durationMinutes: 15,
    theme: "Tanaman",
    constraint: "Kelas berada di samping halaman yang ramai; perhatian anak mudah tersedot suara dari luar.",
    goal: "Merancang tanya jawab pasca-cerita yang singkat, hidup, dan mampu bersaing dengan distraksi sekitar.",
    hints: [
      "Bagaimana posisi duduk dan arah hadap anak bisa mengurangi godaan menoleh ke luar?",
      "Bisakah pertanyaan dijawab dengan gerakan tubuh, bukan hanya kata-kata?",
      "Berapa lama rentang tanya jawab yang realistis untuk usia 3-4 tahun, dan apa tanda saatnya berhenti?",
    ],
  },
];
