import type { StoryFrameworkSeed } from "./types";

export const stories: StoryFrameworkSeed[] = [
  {
    slug: "kiko-kancil-berbagi-timun",
    title: "Kiko Kancil dan Sekeranjang Timun",
    summary:
      "Kiko si kancil kecil menemukan sekeranjang timun di kebun dan belajar bahwa berbagi membuat makanan terasa lebih nikmat.",
    ageMinMonths: 36,
    ageMaxMonths: 60,
    durationMin: 5,
    durationMax: 10,
    themes: ["Binatang", "Makanan", "Teman"],
    values: ["berbagi", "empati"],
    openingQuestion: "Kalau punya makanan enak, teman-teman mau makan sendiri atau berbagi?",
    characters: ["Kiko si kancil kecil", "Momo si monyet", "Bu Tupai"],
    setting: "Kebun timun di pinggir hutan yang cerah",
    plotBeats: [
      "Kiko si kancil menemukan sekeranjang timun segar di pinggir kebun.",
      "Kiko senang sekali dan berencana memakan semuanya sendirian.",
      "Momo si monyet datang dengan perut lapar, tapi Kiko menyembunyikan keranjangnya.",
      "Saat makan sendirian, Kiko merasa timunnya kurang enak dan hatinya sepi.",
      "Bu Tupai lewat sambil membagikan kacang kepada semua hewan dengan wajah gembira.",
      "Kiko teringat Momo, lalu berlari mencarinya dan mengajaknya makan timun bersama.",
      "Mereka makan bersama sambil tertawa; timunnya terasa jauh lebih segar dan manis.",
    ],
    interactionPoints: [
      "Menurut teman-teman, kenapa ya timunnya terasa kurang enak waktu Kiko makan sendirian?",
      "Apa yang sebaiknya Kiko lakukan waktu Momo datang kelaparan?",
      "Coba tirukan wajah Momo yang senang diajak makan bersama!",
    ],
    gestures: [
      "Gerakan mengunyah timun dengan pipi menggembung",
      "Ekspresi sepi dengan bahu turun dan wajah murung",
      "Gerakan berlari kecil di tempat saat Kiko mencari Momo",
      "Tertawa bersama sambil menepuk perut kenyang",
    ],
    closingQuestions: [
      "Apa yang membuat Kiko akhirnya senang?",
      "Kalau di kelas, apa saja yang bisa kita bagi dengan teman?",
    ],
    message: "Makanan sederhana terasa istimewa saat dinikmati bersama teman.",
    followUpActivity:
      "Makan bekal bersama sambil setiap anak menawarkan satu potong kecil bekalnya kepada teman di sebelahnya (perhatikan alergi).",
  },
  {
    slug: "lila-ombak-kecil-yang-berani",
    title: "Lila dan Ombak Kecil yang Berani",
    summary:
      "Lila, anak nelayan, takut menyentuh air laut sampai seekor ombak kecil bernama Ola mengajaknya berkenalan pelan-pelan.",
    ageMinMonths: 42,
    ageMaxMonths: 66,
    durationMin: 7,
    durationMax: 12,
    themes: ["Air", "Alam", "Emosi"],
    values: ["berani", "sabar"],
    openingQuestion: "Siapa yang pernah bermain di pantai? Bagaimana rasanya air laut di kaki?",
    characters: ["Lila anak pesisir", "Ola si ombak kecil", "Ayah Lila sang nelayan"],
    setting: "Pantai berpasir putih di kampung nelayan saat pagi hari",
    plotBeats: [
      "Lila selalu menemani Ayah ke pantai, tapi ia hanya berani duduk jauh dari air.",
      "Teman-temannya bermain di tepi air, Lila ingin ikut tapi kakinya terasa berat.",
      "Ombak kecil bernama Ola menyapa Lila dengan percikan lembut yang menggelitik.",
      "Ola mengajak bermain pelan-pelan: sentuh dengan satu jari kaki dulu.",
      "Lila mencoba satu jari, lalu telapak kaki, lalu berdiri sampai mata kaki.",
      "Ombak datang sedikit lebih besar, Lila kaget, tapi ia ingat bisa mundur kapan saja.",
      "Lila tertawa bermain kejar-kejaran dengan Ola, dan Ayah melambai bangga dari perahu.",
    ],
    interactionPoints: [
      "Bagian tubuh mana yang mau kalian celupkan duluan kalau jadi Lila?",
      "Yuk bantu Lila menghitung: satu jari... dua jari... berapa jari kaki kita semuanya?",
      "Apa yang boleh Lila lakukan kalau ombaknya terasa terlalu besar?",
    ],
    gestures: [
      "Gerakan tangan bergelombang menirukan ombak",
      "Menjulurkan satu jari kaki pelan-pelan dengan wajah ragu",
      "Ekspresi kaget lalu lega",
      "Melambaikan tangan seperti Ayah dari kejauhan",
    ],
    closingQuestions: [
      "Bagaimana cara Lila belajar berani? Langsung ke air dalam atau pelan-pelan?",
      "Apa hal baru yang ingin teman-teman coba pelan-pelan?",
    ],
    message: "Keberanian bisa tumbuh selangkah demi selangkah, dimulai dari langkah paling kecil.",
    followUpActivity:
      "Bermain 'ombak datang': anak-anak melompati kain biru yang digoyang pelan lalu makin cepat sesuai kesiapan masing-masing.",
  },
  {
    slug: "bimo-dan-kelereng-yang-bukan-miliknya",
    title: "Bimo dan Kelereng yang Bukan Miliknya",
    summary:
      "Bimo menemukan kelereng indah di halaman sekolah dan belajar kelegaan berkata jujur ketika tahu kelereng itu milik temannya.",
    ageMinMonths: 48,
    ageMaxMonths: 72,
    durationMin: 7,
    durationMax: 12,
    themes: ["Sekolah", "Teman", "Kebiasaan baik"],
    values: ["jujur", "empati"],
    openingQuestion: "Pernahkah teman-teman menemukan barang yang bukan milik kalian? Apa yang kalian lakukan?",
    characters: ["Bimo", "Sari", "Bu Guru Rina"],
    setting: "Halaman sekolah PAUD di kota kecil, saat jam bermain",
    plotBeats: [
      "Bimo menemukan kelereng biru berkilau di bawah pohon mangga sekolah.",
      "Bimo memasukkan kelereng ke saku; ia sudah lama ingin kelereng seperti itu.",
      "Di kelas, Sari mencari-cari sesuatu sambil hampir menangis: kelereng kesayangannya hilang.",
      "Dada Bimo terasa berat dan tidak nyaman; kelereng di saku seperti semakin berat.",
      "Bimo ragu, lalu memberanikan diri bercerita kepada Bu Guru Rina.",
      "Bu Guru Rina berterima kasih atas kejujuran Bimo dan menemaninya mengembalikan kelereng.",
      "Sari senang sekali, dan mengajak Bimo bermain kelereng bersama sepulang kegiatan.",
    ],
    interactionPoints: [
      "Kira-kira kenapa ya dada Bimo terasa berat dan tidak enak?",
      "Apa yang sebaiknya Bimo lakukan dengan kelereng itu?",
      "Bagaimana perasaan Sari waktu kelerengnya kembali?",
    ],
    gestures: [
      "Gerakan memungut kelereng dan mengamatinya dengan mata berbinar",
      "Memegang dada dengan wajah gelisah",
      "Gerakan menyerahkan kelereng dengan dua tangan",
      "Wajah lega dan senyum lebar",
    ],
    closingQuestions: [
      "Bagaimana rasanya setelah Bimo berkata jujur?",
      "Kalau menemukan barang di sekolah, kepada siapa kita menyerahkannya?",
    ],
    message: "Berkata jujur membuat hati terasa ringan dan pertemanan semakin erat.",
    followUpActivity:
      "Bermain peran 'pos barang temuan': anak bergiliran menemukan benda kelas dan menyerahkannya ke pos sambil mengucapkan kalimat jujur.",
  },
  {
    slug: "tuti-tunas-yang-tidak-sabar",
    title: "Tuti si Tunas yang Tidak Sabar",
    summary:
      "Tuti si tunas kacang ingin cepat tinggi seperti pohon kelapa, dan belajar bahwa tumbuh butuh waktu, air, dan kesabaran.",
    ageMinMonths: 36,
    ageMaxMonths: 60,
    durationMin: 5,
    durationMax: 10,
    themes: ["Tanaman", "Alam", "Kebiasaan baik"],
    values: ["sabar", "syukur"],
    openingQuestion: "Siapa yang pernah menanam biji? Apa yang terjadi setelah berhari-hari?",
    characters: ["Tuti si tunas kacang", "Kek Kelapa si pohon tua", "Riri si rintik hujan"],
    setting: "Kebun sayur di belakang rumah panggung di kampung",
    plotBeats: [
      "Tuti si tunas kacang baru muncul dari tanah, kecil dan melengkung.",
      "Tuti mendongak melihat Kek Kelapa yang tinggi menjulang dan ingin langsung setinggi itu.",
      "Tuti mencoba menarik-narik badannya sendiri ke atas, tapi malah lelah dan lemas.",
      "Riri si rintik hujan datang menyirami dan berbisik: minum dulu, istirahat dulu.",
      "Matahari menyapa setiap pagi, dan setiap hari daun Tuti bertambah satu demi satu.",
      "Suatu pagi Tuti sadar sulurnya sudah merambat jauh dan berbunga ungu cantik.",
      "Kek Kelapa tersenyum: setiap tanaman tumbuh dengan waktunya sendiri-sendiri.",
    ],
    interactionPoints: [
      "Coba teman-teman jadi tunas kecil yang melengkung... lalu tumbuh sedikit... sedikit lagi!",
      "Apa saja ya yang dibutuhkan Tuti supaya bisa tumbuh?",
      "Berapa daun Tuti sekarang? Ayo hitung bersama!",
    ],
    gestures: [
      "Meringkuk seperti biji lalu perlahan berdiri seperti tunas tumbuh",
      "Gerakan jari menirukan rintik hujan turun",
      "Tangan membuka lebar seperti daun terkena sinar matahari",
    ],
    closingQuestions: [
      "Kenapa Tuti tidak bisa langsung tinggi seperti Kek Kelapa?",
      "Hal apa yang teman-teman pelajari pelan-pelan sampai sekarang bisa?",
    ],
    message: "Semua yang tumbuh butuh waktu; menikmati prosesnya membuat hati tenang.",
    followUpActivity:
      "Menanam biji kacang hijau di kapas basah dan mengamati serta menandai pertumbuhannya setiap pagi.",
  },
  {
    slug: "pasar-pagi-bu-imas-dan-keranjang-ajaib",
    title: "Keranjang Bu Imas di Pasar Pagi",
    summary:
      "Dodo menemani ibunya berbelanja dan membantu Bu Imas penjual sayur yang keranjangnya tumpah, lalu mengenal aneka sayur berwarna-warni.",
    ageMinMonths: 42,
    ageMaxMonths: 66,
    durationMin: 7,
    durationMax: 12,
    themes: ["Sayur", "Warna", "Profesi"],
    values: ["peduli lingkungan", "kerja sama", "empati"],
    openingQuestion: "Siapa yang pernah ikut ke pasar? Apa saja yang kalian lihat di sana?",
    characters: ["Dodo", "Ibu Dodo", "Bu Imas penjual sayur"],
    setting: "Pasar pagi yang ramai di kota kecamatan",
    plotBeats: [
      "Dodo menggandeng Ibu menyusuri pasar pagi yang ramai dan penuh warna.",
      "Tiba-tiba keranjang Bu Imas tersenggol gerobak dan sayurnya berhamburan.",
      "Orang-orang lewat begitu saja karena sedang buru-buru.",
      "Dodo menarik tangan Ibu dan mengajak berhenti untuk membantu.",
      "Sambil memungut, Dodo mengenal nama sayur: wortel oranye, bayam hijau, terong ungu.",
      "Keranjang kembali penuh; Bu Imas mengucapkan terima kasih dengan mata berkaca-kaca.",
      "Bu Imas menghadiahkan satu ikat bayam, dan Dodo pulang dengan hati hangat.",
    ],
    interactionPoints: [
      "Sayur apa saja yang jatuh dari keranjang Bu Imas? Sebutkan warnanya!",
      "Kalau teman-teman jadi Dodo, apa yang akan kalian lakukan?",
      "Ayo bantu Dodo memungut: satu wortel, dua wortel... berapa semuanya?",
    ],
    gestures: [
      "Gerakan berjalan riang sambil menggandeng tangan",
      "Ekspresi kaget saat keranjang tumpah",
      "Gerakan memungut dan memasukkan sayur ke keranjang",
      "Membungkuk kecil sambil mengucapkan terima kasih",
    ],
    closingQuestions: [
      "Bagaimana perasaan Bu Imas saat Dodo membantunya?",
      "Sayur warna apa yang paling ingin kalian coba makan?",
    ],
    message: "Bantuan kecil dari tangan kecil bisa sangat berarti bagi orang lain.",
    followUpActivity:
      "Bermain 'pasar-pasaran' dengan sayur asli atau gambar: anak bergiliran menjadi penjual dan pembeli yang saling membantu.",
  },
  {
    slug: "rara-dan-rumah-yang-rapi",
    title: "Rara dan Rumah Mainan yang Berantakan",
    summary:
      "Mainan Rara selalu berserakan sampai suatu hari boneka kesayangannya 'hilang', dan Rara menemukan serunya membereskan mainan ke rumahnya masing-masing.",
    ageMinMonths: 36,
    ageMaxMonths: 54,
    durationMin: 5,
    durationMax: 8,
    themes: ["Rumah", "Kebiasaan baik", "Kebersihan"],
    values: ["mandiri", "kebersihan"],
    openingQuestion: "Di mana teman-teman menyimpan mainan setelah selesai bermain?",
    characters: ["Rara", "Boneka Uni si penyu", "Kak Sena kakak Rara"],
    setting: "Ruang bermain di rumah sederhana yang hangat",
    plotBeats: [
      "Rara bermain seharian; mainan berserakan di seluruh ruangan.",
      "Saat mau tidur siang, Rara mencari Uni si boneka penyu, tapi tidak ketemu.",
      "Rara mencari sambil tersandung balok dan menginjak krayon; wah, susahnya!",
      "Kak Sena mengajak mencari sambil membereskan: balok pulang ke kotak, krayon pulang ke kaleng.",
      "Semakin rapi ruangan, semakin mudah mencari; akhirnya Uni ditemukan di bawah tumpukan baju mainan.",
      "Rara memeluk Uni dan memandang ruangan yang lapang: ternyata rapi itu menyenangkan.",
    ],
    interactionPoints: [
      "Di mana ya kira-kira Uni bersembunyi? Ayo tebak!",
      "Balok pulangnya ke mana? Kalau krayon ke mana?",
      "Kenapa Uni tadi susah sekali ditemukan?",
    ],
    gestures: [
      "Gerakan mencari dengan tangan di dahi menengok kiri-kanan",
      "Melangkah hati-hati seperti melewati mainan berserakan",
      "Gerakan memasukkan benda ke kotak sambil bernyanyi",
      "Memeluk boneka dengan wajah lega",
    ],
    closingQuestions: [
      "Apa enaknya kalau mainan tersimpan di tempatnya?",
      "Mainan apa di kelas kita yang punya 'rumah' sendiri?",
    ],
    message: "Merapikan mainan membuat semua barang mudah ditemukan dan ruang jadi nyaman.",
    followUpActivity:
      "Lomba santai 'antar mainan pulang ke rumahnya' dengan lagu beres-beres sambil mencocokkan mainan dengan label gambar wadahnya.",
  },
  {
    slug: "gagak-gori-dan-sungai-penuh-sampah",
    title: "Gori si Gagak dan Sungai yang Sedih",
    summary:
      "Gori si gagak melihat sungai tempatnya minum penuh sampah plastik, lalu mengajak hewan-hewan kampung bekerja sama membersihkannya.",
    ageMinMonths: 48,
    ageMaxMonths: 72,
    durationMin: 8,
    durationMax: 13,
    themes: ["Lingkungan", "Air", "Binatang"],
    values: ["peduli lingkungan", "kerja sama"],
    openingQuestion: "Ke mana ya perginya sampah yang kita buang sembarangan?",
    characters: ["Gori si gagak", "Beti si bebek", "Kuku si kura-kura", "anak-anak kampung"],
    setting: "Sungai kecil di pinggir kampung yang dulunya jernih",
    plotBeats: [
      "Gori si gagak haus dan terbang menuju sungai kesukaannya.",
      "Sungai itu kini penuh kantong plastik dan botol; airnya keruh dan berbau.",
      "Beti si bebek tidak bisa berenang lincah, kakinya tersangkut plastik.",
      "Kuku si kura-kura hampir memakan plastik yang dikiranya ubur-ubur.",
      "Gori berseru mengumpulkan teman-teman: kita bersihkan sungai kita!",
      "Setiap hewan bekerja sesuai kemampuannya: Gori memungut dari udara, Beti dari air, Kuku dari dasar.",
      "Anak-anak kampung melihat dan ikut membantu sambil menyediakan karung sampah.",
      "Sungai kembali jernih; semua minum dan bermain air dengan gembira.",
    ],
    interactionPoints: [
      "Apa yang terjadi pada Beti dan Kuku karena sampah plastik?",
      "Siapa yang mau bantu Gori? Tugas apa yang bisa kalian lakukan?",
      "Sampah botol dibuang ke mana sebaiknya?",
    ],
    gestures: [
      "Mengepakkan tangan seperti sayap gagak",
      "Ekspresi sedih memandang sungai kotor sambil menutup hidung",
      "Gerakan memungut sampah dan memasukkan ke karung",
      "Gerakan berenang gembira saat sungai bersih",
    ],
    closingQuestions: [
      "Kenapa sungai bisa penuh sampah?",
      "Apa yang bisa kita lakukan supaya sungai dan selokan tetap bersih?",
    ],
    message: "Alam yang bersih adalah hasil kerja sama semua penghuninya, sekecil apa pun perannya.",
    followUpActivity:
      "Operasi semut di halaman sekolah: memungut sampah dengan sarung tangan dan memilahnya ke wadah sampah yang sesuai.",
  },
  {
    slug: "delman-pak-karta-keliling-kota",
    title: "Delman Pak Karta Keliling Kota",
    summary:
      "Nino naik delman Pak Karta berkeliling kota dan mengenal macam-macam kendaraan sambil belajar sabar menunggu di lampu merah.",
    ageMinMonths: 36,
    ageMaxMonths: 60,
    durationMin: 6,
    durationMax: 10,
    themes: ["Kendaraan", "Kota", "Bunyi"],
    values: ["sabar", "syukur"],
    openingQuestion: "Kendaraan apa yang pernah teman-teman naiki? Bagaimana bunyinya?",
    characters: ["Nino", "Pak Karta kusir delman", "Jali si kuda"],
    setting: "Jalan-jalan kota yang ramai di sore hari",
    plotBeats: [
      "Nino naik delman Pak Karta; Jali si kuda berjalan tuk-tik-tak-tik-tuk.",
      "Di jalan, mereka berpapasan dengan sepeda yang berdering kring-kring.",
      "Bus besar lewat dengan suara brum-brum, dan ambulans meluncur dengan niu-niu-niu.",
      "Di lampu merah, semua kendaraan berhenti; Nino ingin cepat jalan, tapi Pak Karta tersenyum tenang.",
      "Pak Karta bercerita: lampu merah menjaga semua orang bergiliran dengan aman.",
      "Lampu hijau menyala, semua berjalan lagi dengan tertib.",
      "Nino sampai di rumah sambil melambai pada Jali: terima kasih sudah mengantar!",
    ],
    interactionPoints: [
      "Bagaimana bunyi kaki kuda? Ayo tirukan bersama!",
      "Lampu merah artinya apa? Kalau hijau?",
      "Kendaraan apa lagi yang mungkin Nino temui di jalan?",
    ],
    gestures: [
      "Menepuk paha menirukan derap kaki kuda",
      "Gerakan tangan membunyikan bel sepeda",
      "Tangan terbuka tegak menirukan tanda berhenti",
      "Melambaikan tangan perpisahan",
    ],
    closingQuestions: [
      "Kenapa semua kendaraan harus berhenti saat lampu merah?",
      "Siapa yang bekerja mengantar orang-orang setiap hari? Apa ucapan kita untuk mereka?",
    ],
    message: "Menunggu giliran di jalan menjaga semua orang tetap aman.",
    followUpActivity:
      "Bermain lalu lintas: anak berbaris jadi kereta kendaraan, guru mengangkat kartu merah-hijau, anak berhenti dan berjalan sesuai kartu.",
  },
  {
    slug: "wulan-dan-payung-untuk-nenek-ijah",
    title: "Wulan dan Payung untuk Nenek Ijah",
    summary:
      "Saat hujan turun, Wulan melihat Nenek Ijah kehujanan di depan warung dan belajar bahwa peduli bisa dimulai dari satu payung kecil.",
    ageMinMonths: 42,
    ageMaxMonths: 66,
    durationMin: 6,
    durationMax: 10,
    themes: ["Cuaca", "Keluargaku", "Emosi"],
    values: ["empati", "peduli lingkungan"],
    openingQuestion: "Apa yang teman-teman rasakan saat hujan turun? Suka atau tidak?",
    characters: ["Wulan", "Nenek Ijah tetangga", "Ibu Wulan"],
    setting: "Gang kampung di kota saat hujan deras sore hari",
    plotBeats: [
      "Hujan turun deras; Wulan senang menonton rintik dari jendela sambil minum teh hangat.",
      "Di seberang gang, Nenek Ijah berdiri kedinginan di depan warung tanpa payung.",
      "Wulan bertanya-tanya: bagaimana ya rasanya kedinginan menunggu hujan reda?",
      "Wulan mengambil payung dan mengajak Ibu menjemput Nenek Ijah bersama-sama.",
      "Mereka memayungi Nenek Ijah sampai rumahnya sambil melompati genangan kecil.",
      "Nenek Ijah menghangatkan diri dan menghadiahi mereka pisang goreng hangat.",
      "Wulan pulang dengan hati hangat meski bajunya sedikit basah.",
    ],
    interactionPoints: [
      "Bagaimana ya perasaan Nenek Ijah saat kehujanan sendirian?",
      "Apa yang bisa Wulan lakukan untuk membantu?",
      "Ayo lompati genangan! Satu... dua... tiga... hop!",
    ],
    gestures: [
      "Jari-jari bergerak turun menirukan rintik hujan",
      "Gerakan memeluk badan sendiri seperti kedinginan",
      "Gerakan memegang payung berdua",
      "Melompat kecil seperti melewati genangan",
    ],
    closingQuestions: [
      "Kenapa hati Wulan terasa hangat padahal bajunya basah?",
      "Siapa yang bisa kita bantu saat cuaca hujan?",
    ],
    message: "Kepedulian kecil dapat menghangatkan hari orang lain, bahkan di tengah hujan.",
    followUpActivity:
      "Membuat kolase payung dari kertas warna sambil bercerita siapa yang ingin anak lindungi dengan payungnya.",
  },
  {
    slug: "obi-jari-jempol-dan-sabun-wangi",
    title: "Obi dan Pasukan Sabun Wangi",
    summary:
      "Obi malas mencuci tangan sampai ia berkenalan dengan pasukan gelembung sabun yang membantu mengusir kuman tak terlihat dari tangannya.",
    ageMinMonths: 36,
    ageMaxMonths: 54,
    durationMin: 5,
    durationMax: 8,
    themes: ["Kebersihan", "Tubuhku", "Kebiasaan baik"],
    values: ["kebersihan", "mandiri"],
    openingQuestion: "Kapan saja kita perlu mencuci tangan?",
    characters: ["Obi", "Bubu si gelembung sabun", "Ibu Obi"],
    setting: "Rumah Obi, di depan keran air dekat dapur",
    plotBeats: [
      "Obi asyik bermain tanah seharian di halaman; tangannya cokelat kehitaman.",
      "Saat mau makan pisang, Ibu mengingatkan untuk mencuci tangan dulu.",
      "Obi menggerutu: kan tangannya kelihatan cuma sedikit kotor.",
      "Dari sabun muncul Bubu si gelembung: 'Ada tamu tak terlihat di tanganmu, namanya kuman!'",
      "Bubu mengajak Obi menggosok telapak, punggung tangan, sela jari, dan kuku sambil bernyanyi.",
      "Gelembung membawa kuman-kuman pergi bersama air; tangan Obi wangi dan segar.",
      "Pisang terasa lebih nikmat dimakan dengan tangan bersih.",
    ],
    interactionPoints: [
      "Ayo bantu Obi menggosok tangan: telapak, punggung tangan, sela-sela jari!",
      "Kenapa ya kita tetap harus cuci tangan walau tangan kelihatan bersih?",
      "Kita nyanyikan lagu cuci tangan sama-sama yuk!",
    ],
    gestures: [
      "Gerakan menggosok kedua telapak tangan",
      "Menggosok sela-sela jari dengan teliti",
      "Gerakan gelembung terbang dengan jari membentuk lingkaran",
      "Mengendus tangan sendiri sambil tersenyum",
    ],
    closingQuestions: [
      "Bagian tangan mana saja yang harus digosok saat mencuci tangan?",
      "Sebelum apa saja kita perlu mencuci tangan?",
    ],
    message: "Tangan bersih membuat makan lebih nikmat dan badan tetap sehat.",
    followUpActivity:
      "Praktik cuci tangan bersama di keran dengan lagu enam langkah, lalu mencap telapak tangan bersih di kertas dengan cat aman.",
  },
  {
    slug: "juru-masak-cilik-dapur-mbok-darmi",
    title: "Juru Masak Cilik di Dapur Mbok Darmi",
    summary:
      "Sekar membantu Mbok Darmi memasak nasi liwet untuk syukuran kampung dan menemukan bahwa bekerja bersama membuat pekerjaan besar jadi ringan.",
    ageMinMonths: 48,
    ageMaxMonths: 72,
    durationMin: 8,
    durationMax: 13,
    themes: ["Makanan", "Budaya lokal", "Profesi"],
    values: ["kerja sama", "syukur"],
    openingQuestion: "Siapa yang pernah membantu memasak di rumah? Membantu apa?",
    characters: ["Sekar", "Mbok Darmi juru masak kampung", "teman-teman Sekar"],
    setting: "Dapur kayu Mbok Darmi di kampung, menjelang syukuran panen",
    plotBeats: [
      "Kampung akan mengadakan syukuran panen; Mbok Darmi kebagian memasak nasi liwet untuk banyak orang.",
      "Mbok Darmi kewalahan sendirian: beras belum dicuci, daun pisang belum dilap.",
      "Sekar datang bertanya: 'Boleh aku bantu, Mbok?'",
      "Mbok Darmi memberi tugas sesuai kemampuan: Sekar melap daun pisang, temannya menata gelas.",
      "Dapur jadi riuh gembira: ada yang bernyanyi sambil bekerja, harum nasi mulai tercium.",
      "Satu per satu pekerjaan selesai jauh lebih cepat dari biasanya.",
      "Saat syukuran, semua makan bersama; Mbok Darmi berterima kasih pada para juru masak cilik.",
    ],
    interactionPoints: [
      "Tugas apa yang bisa dikerjakan anak-anak untuk membantu Mbok Darmi?",
      "Hmm, harum apa ya yang tercium dari dapur? Coba hirup dalam-dalam!",
      "Kenapa pekerjaannya jadi cepat selesai?",
    ],
    gestures: [
      "Gerakan melap daun pisang dengan hati-hati",
      "Gerakan mengaduk dengan sendok besar",
      "Menghirup aroma masakan dengan mata terpejam",
      "Gerakan makan bersama sambil duduk melingkar",
    ],
    closingQuestions: [
      "Apa yang terjadi kalau Mbok Darmi bekerja sendirian?",
      "Di kelas, pekerjaan apa yang bisa kita kerjakan bersama-sama?",
    ],
    message: "Pekerjaan besar terasa ringan dan gembira bila dikerjakan bersama-sama.",
    followUpActivity:
      "Membuat 'bekal bersama' sederhana: setiap anak kebagian satu tugas kecil seperti menata piring, membagi buah, dan mengelap meja.",
  },
  {
    slug: "kupu-kuning-dan-taman-tiga-warna",
    title: "Kuki si Kupu-Kupu dan Taman Tiga Warna",
    summary:
      "Kuki si kupu-kupu kuning mencari bunga di taman kota dan mengajak anak-anak mengenal warna merah, kuning, biru sambil menolong lebah tersesat.",
    ageMinMonths: 36,
    ageMaxMonths: 54,
    durationMin: 5,
    durationMax: 9,
    themes: ["Warna", "Binatang", "Tanaman"],
    values: ["peduli lingkungan", "berbagi"],
    openingQuestion: "Warna apa yang paling teman-teman suka? Coba tunjuk benda dengan warna itu!",
    characters: ["Kuki si kupu-kupu kuning", "Lele si lebah kecil", "Pak Tukang Kebun"],
    setting: "Taman kota dengan petak bunga merah, kuning, dan biru",
    plotBeats: [
      "Kuki si kupu-kupu terbang mencari sarapan madu di taman kota.",
      "Ia hinggap di petak bunga merah: harum, tapi bukan kesukaannya.",
      "Ia mencoba petak bunga biru: cantik, tapi madunya sedikit.",
      "Di petak bunga kuning, Kuki bertemu Lele si lebah yang menangis karena tersesat.",
      "Kuki berbagi madu sarapannya dan mengajak Lele terbang tinggi melihat arah pulang.",
      "Dari atas, mereka melihat taman seperti pelangi: merah, kuning, biru berjajar.",
      "Lele menemukan rumah lebahnya di pohon rambutan dan berterima kasih pada Kuki.",
    ],
    interactionPoints: [
      "Petak bunga warna apa yang pertama didatangi Kuki?",
      "Ayo bantu Lele: rumahnya di dekat pohon apa ya? Lihat dari atas, tunjuk!",
      "Coba kepakkan sayap seperti Kuki, pelan... lalu cepat!",
    ],
    gestures: [
      "Mengepakkan kedua tangan seperti sayap kupu-kupu",
      "Mengendus bunga dengan mata terpejam",
      "Ekspresi menenangkan teman yang menangis",
      "Tangan memayungi mata melihat dari ketinggian",
    ],
    closingQuestions: [
      "Warna bunga apa saja yang ada di taman?",
      "Apa yang Kuki lakukan saat bertemu Lele yang sedih?",
    ],
    message: "Sambil bermain dan menjelajah, kita selalu bisa berhenti untuk menolong teman.",
    followUpActivity:
      "Berburu warna di kelas atau halaman: anak mencari dan mengelompokkan benda merah, kuning, dan biru ke keranjang yang sesuai.",
  },
  {
    slug: "topi-caping-pak-tani-dan-burung-pipit",
    title: "Topi Caping Pak Tani dan Burung Pipit",
    summary:
      "Pak Tani kesal pada burung pipit pemakan padi, sampai ia menemukan cara berbagi hasil kebun tanpa ada yang kelaparan.",
    ageMinMonths: 48,
    ageMaxMonths: 72,
    durationMin: 8,
    durationMax: 14,
    themes: ["Tanaman", "Binatang", "Profesi"],
    values: ["berbagi", "sabar", "empati"],
    openingQuestion: "Dari mana ya asalnya nasi yang kita makan setiap hari?",
    characters: ["Pak Tani Sabar", "Pipit si burung kecil", "keluarga burung pipit"],
    setting: "Sawah menghijau di kaki bukit dengan orang-orangan sawah",
    plotBeats: [
      "Padi Pak Tani mulai menguning; sebentar lagi panen tiba.",
      "Kawanan burung pipit datang mematuk bulir padi setiap pagi.",
      "Pak Tani memasang orang-orangan sawah, tapi pipit tidak takut lagi setelah beberapa hari.",
      "Pak Tani duduk kesal, lalu memperhatikan: pipit-pipit itu menyuapi anak-anaknya yang lapar.",
      "Hati Pak Tani tersentuh; ia berpikir mencari jalan supaya semua kebagian.",
      "Pak Tani menanam padi tambahan di petak kecil pinggir sawah khusus untuk burung.",
      "Pipit makan di petak pinggir, padi utama aman, dan sawah jadi ramai kicau yang riang.",
      "Saat panen, Pak Tani tersenyum: hasilnya cukup, hatinya pun lapang.",
    ],
    interactionPoints: [
      "Kenapa burung pipit terus datang ke sawah Pak Tani?",
      "Kalau jadi Pak Tani, apa yang akan teman-teman lakukan?",
      "Ayo tirukan suara pipit yang kenyang dan gembira: cit-cit-cit!",
    ],
    gestures: [
      "Berdiri tegak dengan tangan terentang seperti orang-orangan sawah",
      "Gerakan paruh mematuk dengan tangan",
      "Ekspresi kesal berubah menjadi iba lalu tersenyum",
      "Gerakan menabur benih di petak kecil",
    ],
    closingQuestions: [
      "Bagaimana cara Pak Tani berbagi dengan burung pipit?",
      "Menurut kalian, kenapa Pak Tani akhirnya merasa senang?",
    ],
    message: "Ketika kita berbagi rezeki secukupnya, semua makhluk bisa hidup berdampingan.",
    followUpActivity:
      "Membuat orang-orangan sawah mini dari stik dan kain perca, lalu menaruh remah biji-bijian di wadah untuk burung di halaman.",
  },
  {
    slug: "sepatu-baru-arka-dan-kaki-yang-hebat",
    title: "Arka dan Kedua Kaki yang Hebat",
    summary:
      "Arka mengeluh capek berjalan ke sekolah sampai kakek mengajaknya bermain menghitung langkah dan mensyukuri tubuh yang bisa bergerak.",
    ageMinMonths: 36,
    ageMaxMonths: 60,
    durationMin: 5,
    durationMax: 9,
    themes: ["Tubuhku", "Aku", "Angka"],
    values: ["syukur", "mandiri"],
    openingQuestion: "Apa saja yang bisa dilakukan kaki kita? Ayo sebutkan!",
    characters: ["Arka", "Kakek Arka", "Cici si cicak di dinding sekolah"],
    setting: "Jalan setapak dari rumah ke sekolah melewati kebun singkong",
    plotBeats: [
      "Arka menggerutu karena jalan ke sekolah terasa jauh dan melelahkan.",
      "Kakek mengajak bermain: menghitung langkah dari pohon jambu sampai pagar sekolah.",
      "Satu, dua, tiga... Arka melangkah sambil menghitung dan lupa lelahnya.",
      "Mereka berjingkat seperti kucing, melompat seperti katak, dan berjalan mundur pelan.",
      "Di sekolah, Cici si cicak menyapa dari dinding: 'Kakimu hebat, bisa melompat dan berlari!'",
      "Arka memandang kakinya dan tersenyum: kaki kecilnya bisa melakukan banyak hal.",
      "Pulangnya, Arka yang mengajak Kakek berlomba jalan cepat sampai rumah.",
    ],
    interactionPoints: [
      "Ayo bantu Arka menghitung langkah: satu, dua, tiga... sampai sepuluh!",
      "Coba berjingkat seperti kucing... sekarang melompat seperti katak!",
      "Apa saja yang bisa dilakukan kaki teman-teman?",
    ],
    gestures: [
      "Berjalan di tempat sambil menghitung dengan jari",
      "Berjingkat pelan dengan telunjuk di bibir",
      "Melompat kecil dua kali",
      "Menunjuk dan menggerakkan kaki dengan bangga",
    ],
    closingQuestions: [
      "Kenapa Arka tidak merasa lelah lagi?",
      "Bagaimana cara kita merawat kaki kita?",
    ],
    message: "Tubuh kita adalah hadiah berharga; bergerak dan bermain adalah cara merayakannya.",
    followUpActivity:
      "Jalur langkah seru: anak melewati lintasan dengan berjingkat, melompat, dan berjalan mundur sambil menghitung langkah bersama.",
  },
  {
    slug: "bende-kecil-di-hari-kemerdekaan",
    title: "Bendera Kecil Salsa di Hari Kemerdekaan",
    summary:
      "Salsa dan teman-teman menyiapkan lomba tujuh belasan di kampung dan belajar bahwa merayakan Indonesia bisa dengan gotong royong yang gembira.",
    ageMinMonths: 48,
    ageMaxMonths: 72,
    durationMin: 8,
    durationMax: 13,
    themes: ["Indonesia", "Budaya lokal", "Teman"],
    values: ["kerja sama", "syukur"],
    openingQuestion: "Apa warna bendera Indonesia? Siapa pernah ikut lomba tujuh belasan?",
    characters: ["Salsa", "Bang Udin pemuda kampung", "teman-teman Salsa"],
    setting: "Lapangan kampung yang dihias menjelang 17 Agustus",
    plotBeats: [
      "Kampung Salsa bersiap merayakan hari kemerdekaan; lapangan akan dihias.",
      "Bang Udin membagi tugas: ada yang memasang bendera kecil, ada yang meniup balon.",
      "Salsa kebagian menghias gapura, tapi tangannya belum sampai ke bagian atas.",
      "Teman-temannya bergantian: yang tinggi memasang atas, Salsa menghias bagian bawah.",
      "Angin bertiup dan beberapa bendera kertas terlepas; semua bekerja sama memungut dan memasang ulang.",
      "Sore harinya lapangan meriah merah-putih; anak-anak berlatih baris dengan riang.",
      "Esoknya lomba balap karung dimulai; menang atau belum menang, semua tertawa gembira.",
    ],
    interactionPoints: [
      "Tugas apa yang cocok untuk Salsa yang badannya belum tinggi?",
      "Wah, benderanya terlepas tertiup angin! Apa yang harus dilakukan?",
      "Ayo berlatih baris: tegak... hormat... jalan di tempat!",
    ],
    gestures: [
      "Gerakan memasang bendera kecil satu per satu",
      "Meniup balon dengan pipi menggembung",
      "Gerakan melompat dalam karung",
      "Sikap hormat bendera dengan tegak",
    ],
    closingQuestions: [
      "Apa saja yang dilakukan warga bersama-sama untuk perayaan?",
      "Bagaimana perasaan teman-teman kalau ikut lomba walau belum menang?",
    ],
    message: "Kegembiraan merayakan negeri lahir dari kebersamaan, bukan dari siapa yang menang.",
    followUpActivity:
      "Membuat bendera merah-putih dari kertas lipat dan mengadakan lomba mini balap karung atau estafet bendera di halaman.",
  },
  {
    slug: "gong-dan-gamelan-mbah-surya",
    title: "Nada Pertama Gilang di Rumah Gamelan",
    summary:
      "Gilang mengunjungi sanggar gamelan Mbah Surya, mengenal bunyi gong, saron, dan kendang, lalu belajar menunggu giliran memukul dengan tepat.",
    ageMinMonths: 48,
    ageMaxMonths: 72,
    durationMin: 8,
    durationMax: 14,
    themes: ["Budaya lokal", "Bunyi", "Indonesia"],
    values: ["sabar", "kerja sama"],
    openingQuestion: "Bunyi musik apa yang pernah teman-teman dengar? Bagaimana bunyinya?",
    characters: ["Gilang", "Mbah Surya penabuh gamelan", "anak-anak sanggar"],
    setting: "Pendopo sanggar gamelan di kampung budaya",
    plotBeats: [
      "Gilang mendengar bunyi gung... gung... dari pendopo dan mengintip penasaran.",
      "Mbah Surya mengajaknya masuk dan memperkenalkan alat-alat: gong besar, saron berbilah, kendang bertabuh tangan.",
      "Gilang ingin langsung memukul semuanya keras-keras.",
      "Mbah Surya tersenyum: gamelan indah kalau semua menunggu gilirannya masing-masing.",
      "Anak-anak sanggar bermain bergiliran: kendang dulu, lalu saron, lalu gong pada hitungan tepat.",
      "Gilang kebagian gong; ia menunggu... menunggu... dan gung! Tepat pada waktunya.",
      "Semua tersenyum; bunyi yang berbeda-beda menyatu menjadi musik yang indah.",
    ],
    interactionPoints: [
      "Coba tirukan bunyi gong! Sekarang bunyi kendang: dung-tak-dung!",
      "Kenapa ya Gilang harus menunggu giliran memukul gong?",
      "Ayo hitung bersama sampai giliran gong: satu, dua, tiga, empat... gung!",
    ],
    gestures: [
      "Gerakan memukul gong besar dengan ayunan pelan",
      "Menepuk paha bergantian menirukan kendang",
      "Telunjuk di bibir sambil menunggu hitungan",
      "Mengangguk-angguk mengikuti irama",
    ],
    closingQuestions: [
      "Alat musik apa saja yang ada di sanggar Mbah Surya?",
      "Apa yang terjadi kalau semua memukul sesukanya tanpa menunggu giliran?",
    ],
    message: "Bunyi yang berbeda-beda menjadi indah ketika semua bermain saling mendengarkan.",
    followUpActivity:
      "Membuat 'gamelan kelas' dari kaleng, botol, dan galon bekas, lalu bermain irama bergiliran mengikuti aba-aba guru.",
  },
  {
    slug: "rumah-pohon-empat-sahabat",
    title: "Rumah Pohon Empat Sahabat",
    summary:
      "Empat sahabat berbeda kesukaan berselisih tentang bentuk rumah pohon impian, lalu menemukan cara menggabungkan ide semua orang.",
    ageMinMonths: 48,
    ageMaxMonths: 72,
    durationMin: 8,
    durationMax: 13,
    themes: ["Teman", "Bentuk", "Rumah"],
    values: ["kerja sama", "empati"],
    openingQuestion: "Kalau boleh membangun rumah impian, bentuknya seperti apa?",
    characters: ["Niko", "Ayu", "Tomi", "Rini", "Pak Guru Harun"],
    setting: "Halaman belakang sekolah dengan pohon jambu besar",
    plotBeats: [
      "Empat sahabat ingin membuat rumah-rumahan di bawah pohon jambu sekolah.",
      "Niko mau jendela bundar, Ayu mau atap segitiga, Tomi mau pintu kotak, Rini mau hiasan bintang.",
      "Mereka berdebat; masing-masing merasa idenya yang paling bagus, dan hampir batal bermain.",
      "Pak Guru Harun bertanya: 'Bagaimana kalau rumahnya punya semuanya?'",
      "Mereka menggambar rencana bersama: atap segitiga, pintu kotak, jendela bundar, hiasan bintang.",
      "Setiap anak mengerjakan bagian kesukaannya dari kardus dan kain bekas.",
      "Rumah-rumahan selesai, unik dan tidak ada duanya; semua merasa itu rumah miliknya.",
    ],
    interactionPoints: [
      "Bentuk apa saja yang diinginkan keempat sahabat? Ayo tunjuk bentuknya di kelas!",
      "Bagaimana caranya supaya semua ide bisa dipakai?",
      "Coba buat bentuk segitiga dengan tangan... sekarang lingkaran!",
    ],
    gestures: [
      "Membentuk segitiga, kotak, dan lingkaran dengan kedua tangan",
      "Ekspresi cemberut saat berdebat lalu mencair jadi senyum",
      "Gerakan menggunting dan menempel",
      "Merentangkan tangan bangga memandang hasil karya",
    ],
    closingQuestions: [
      "Kenapa rumah pohon mereka jadi istimewa?",
      "Apa yang terjadi kalau mereka terus berdebat dan tidak mau mendengar ide teman?",
    ],
    message: "Ide yang berbeda-beda bisa disatukan menjadi karya yang lebih istimewa.",
    followUpActivity:
      "Membangun rumah-rumahan kelompok dari kardus: setiap anak menyumbang satu bentuk (segitiga, kotak, lingkaran, bintang) untuk ditempel.",
  },
  {
    slug: "puput-angin-dan-layang-layang-adit",
    title: "Puput si Angin dan Layang-Layang Adit",
    summary:
      "Adit belajar bahwa angin yang tak terlihat itu nyata dan sangat berguna, saat Puput si angin membantu layang-layangnya terbang di tanah lapang.",
    ageMinMonths: 42,
    ageMaxMonths: 66,
    durationMin: 6,
    durationMax: 11,
    themes: ["Udara", "Alam", "Cuaca"],
    values: ["sabar", "syukur"],
    openingQuestion: "Kita tidak bisa melihat angin, tapi bagaimana kita tahu angin itu ada?",
    characters: ["Adit", "Puput si angin sepoi", "Kak Raras"],
    setting: "Tanah lapang berumput di pinggir kampung saat sore",
    plotBeats: [
      "Adit membawa layang-layang barunya ke tanah lapang dengan semangat.",
      "Ia berlari kencang, tapi layang-layangnya jatuh terus; udara sedang diam.",
      "Adit hampir menyerah dan duduk cemberut di rumput.",
      "Puput si angin datang pelan: rumput bergoyang, topi Adit bergetar, daun kering menari.",
      "Kak Raras berbisik: 'Rasakan dulu arah angin, baru lepaskan layang-layangnya.'",
      "Adit menunggu, merasakan angin di pipinya, lalu mengulur benang perlahan.",
      "Layang-layang naik tinggi meliuk-liuk; Adit bersorak dan berterima kasih pada angin.",
    ],
    interactionPoints: [
      "Dari mana kita tahu Puput si angin sudah datang? Apa saja yang bergerak?",
      "Ayo tiup telapak tangan masing-masing... terasa anginnya?",
      "Kapan waktu yang tepat bagi Adit melepas layang-layang?",
    ],
    gestures: [
      "Meniup pelan ke telapak tangan sendiri",
      "Tangan meliuk seperti layang-layang terbang",
      "Gerakan mengulur benang perlahan",
      "Menengadah sambil memayungi mata memandang langit",
    ],
    closingQuestions: [
      "Apa saja gunanya angin selain menerbangkan layang-layang?",
      "Kenapa Adit akhirnya berhasil?",
    ],
    message: "Ada banyak hal berharga yang tidak terlihat mata, tapi bisa kita rasakan dan syukuri.",
    followUpActivity:
      "Membuat kincir angin kertas sederhana dan mengamatinya berputar saat ditiup atau dibawa berjalan di halaman.",
  },
  {
    slug: "sarapan-buah-naga-untuk-adik",
    title: "Kejutan Buah untuk Adik Alya",
    summary:
      "Alya menyiapkan piring buah warna-warni untuk adiknya yang susah makan buah, dan menemukan cara membuat sarapan jadi permainan seru.",
    ageMinMonths: 36,
    ageMaxMonths: 60,
    durationMin: 5,
    durationMax: 9,
    themes: ["Buah", "Keluargaku", "Makanan"],
    values: ["peduli lingkungan", "berbagi", "mandiri"],
    openingQuestion: "Buah apa yang paling teman-teman suka? Apa warnanya?",
    characters: ["Alya", "Dede adik Alya", "Ayah Alya"],
    setting: "Dapur dan meja makan rumah Alya di pagi hari",
    plotBeats: [
      "Dede si adik menutup mulut rapat-rapat setiap disodori buah.",
      "Alya ingin membantu; ia mengajak Ayah memilih buah di keranjang: pepaya oranye, pisang kuning, semangka merah.",
      "Alya menata potongan buah di piring membentuk wajah tersenyum: mata pisang, mulut semangka.",
      "Dede melirik piring lucu itu dan mulai penasaran.",
      "Alya mengajak bermain: 'Ayo makan matanya dulu! Aaa...'",
      "Dede mencoba sepotong, lalu sepotong lagi; ternyata manis dan segar.",
      "Piring wajah tersenyum tandas; Dede tersenyum selebar gambar di piringnya.",
    ],
    interactionPoints: [
      "Buah apa yang dipakai untuk mata? Untuk mulut?",
      "Kenapa ya Dede jadi mau mencoba buahnya?",
      "Kalau kalian, mau menyusun buah jadi bentuk apa?",
    ],
    gestures: [
      "Menutup mulut rapat dengan dua tangan seperti Dede",
      "Gerakan menata potongan buah dengan hati-hati",
      "Gerakan menyuap dengan 'Aaa...'",
      "Menepuk perut kenyang sambil tersenyum",
    ],
    closingQuestions: [
      "Bagaimana cara Alya membuat adiknya mau makan buah?",
      "Buah apa yang ingin kalian coba besok pagi?",
    ],
    message: "Perhatian dan sedikit ide kreatif bisa membuat hal sehat jadi menyenangkan.",
    followUpActivity:
      "Menyusun potongan buah (disiapkan guru) menjadi bentuk wajah di piring kecil lalu memakannya bersama-sama.",
  },
  {
    slug: "hompimpa-di-bawah-beringin",
    title: "Hompimpa di Bawah Pohon Beringin",
    summary:
      "Anak-anak kampung memperkenalkan permainan tradisional kepada Niluh, anak pindahan, yang awalnya merasa asing dan takut tidak punya teman.",
    ageMinMonths: 42,
    ageMaxMonths: 66,
    durationMin: 6,
    durationMax: 11,
    themes: ["Budaya lokal", "Teman", "Emosi"],
    values: ["empati", "berani", "kerja sama"],
    openingQuestion: "Bagaimana rasanya menjadi anak baru yang belum punya teman?",
    characters: ["Niluh anak pindahan", "Jaka", "Ema", "anak-anak kampung"],
    setting: "Halaman luas di bawah pohon beringin tua di tengah kampung",
    plotBeats: [
      "Niluh baru pindah ke kampung; sore itu ia berdiri malu-malu memandang anak-anak bermain.",
      "Jaka melihat Niluh dan mengajaknya mendekat: 'Ayo main bersama kami!'",
      "Anak-anak mengajarkan hompimpa untuk membagi kelompok dengan adil.",
      "Mereka bermain engklek; Niluh belum bisa, dan lemparannya meleset terus.",
      "Ema menemani berlatih pelan-pelan: cara melempar pecahan genting, cara melompat satu kaki.",
      "Giliran berikutnya, lemparan Niluh tepat di kotak; semua bersorak untuknya.",
      "Matahari terbenam; mereka pulang sambil berjanji bermain lagi besok, kini bersama Niluh.",
    ],
    interactionPoints: [
      "Ayo kita hompimpa bersama: hompimpa alaium gambreng!",
      "Apa yang dilakukan Ema saat Niluh belum bisa bermain?",
      "Coba berdiri dan melompat dengan satu kaki seperti main engklek!",
    ],
    gestures: [
      "Gerakan hompimpa dengan membalik telapak tangan",
      "Melompat satu kaki di tempat",
      "Gerakan melempar pelan dengan bidikan",
      "Bersorak sambil mengangkat kedua tangan",
    ],
    closingQuestions: [
      "Bagaimana perasaan Niluh di awal cerita? Bagaimana di akhir?",
      "Kalau ada teman baru di kelas kita, apa yang bisa kita lakukan?",
    ],
    message: "Ajakan bermain yang tulus bisa mengubah hari yang sepi menjadi hari yang hangat.",
    followUpActivity:
      "Bermain engklek sederhana dengan kotak lakban di lantai atau kapur di halaman, dimulai dengan hompimpa bersama.",
  },
];
